microADB/hal: fix compile error.
BUILD CMD: ./tools/configure.sh -l sim/adb; make -j`nproc`

microADB/hal/hal_uv_socket.c: In function 'adb_hal_socket_connect':
 microADB/hal/hal_uv_socket.c:145:18: error: unused variable 'handle' [-Werror=unused-variable]
 145 | uv_handle_t *handle = (uv_handle_t*)(((adb_client_uv_t*)client)+1);
 | ^~~~~~
 microADB/hal/hal_uv_socket.c: At top level:
 microADB/hal/hal_uv_socket.c:48:13: error: 'tcp_stream_on_data_available' defined but not used [-Werror=unused-function]
 48 | static void tcp_stream_on_data_available(uv_stream_t* handle,
 | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
 microADB/hal/hal_uv_socket.c:29:13: error: 'tcp_stream_allocate_frame' defined but not used [-Werror=unused-function]
 29 | static void tcp_stream_allocate_frame(uv_handle_t* handle,
 | ^~~~~~~~~~~~~~~~~~~~~~~~~
 cc1: all warnings being treated as errors
230 | int ret;
 | ^~~
 cc1: all warnings being treated as errors
 make[2]: *** [/home/work/ssd1/workspace/Vela-Multi-Boards-dev-system-CI/apps/Application.mk:251: microADB/hal/shell_service_uv.c.home.work.ssd1.workspace.Vela-Multi-Boards-dev-system-CI.apps.system.adb.o] Error 1
 make[2]: Target 'all' not remade because of errors.
 make[1]: *** [Makefile:52: /home/work/ssd1/workspace/Vela-Multi-Boards-dev-system-CI/apps/system/adb_all] Error 2
 make[1]: Target 'all' not remade because of errors.
 make: *** [tools/LibTargets.mk:248: /home/work/ssd1/workspace/Vela-Multi-Boards-dev-system-CI/apps/libapps.a] Error 2
 make: Target 'all' not remade because of errors.
 /home/work/ssd1/workspace/Vela-Multi-Boards-dev-system-CI/nuttx/tools/testbuild.sh: line 385: /home/work/ssd1/workspace/Vela-Multi-Boards-dev-system-CI/nuttx/../nuttx/nuttx.manifest: No such file or directory

Signed-off-by: wangzhi16 <wangzhi16@xiaomi.com>